# Generated by Django 3.1.4 on 2021-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.ManyToManyField(to='shoestore.sizes'),
        ),
    ]
