# Generated by Django 3.1.4 on 2021-02-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0002_color_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='size',
        ),
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.CharField(choices=[('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('12', '12')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
