# Generated by Django 3.1.4 on 2021-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0003_auto_20210205_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='size',
        ),
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.ManyToManyField(to='shoestore.sizes'),
        ),
    ]
