# Generated by Django 3.1.4 on 2021-02-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0006_remove_cart_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
