# Generated by Django 3.1.4 on 2021-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0008_cart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media/category'),
            preserve_default=False,
        ),
    ]
