# Generated by Django 3.1.4 on 2021-02-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0009_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
    ]
