# Generated by Django 3.1.4 on 2021-02-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0010_remove_cart_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='head4',
        ),
    ]
